### PR TITLE
lockes_thethief update

### PR DESCRIPTION
**Pull request by Lockeheede**
->updated namesList

# Examinee

Add your discord name here: lockes_thethief
Add your name on the Trello board here: lockes_thethief
Add your GItHub account name here: Lockeheede

# Reviewing the exam

As a reviewer you want to make sure:
- That the person has cloned the project, not forked it.
- That you can access their branch without problems.
- That they have changed ONLY the list of names and nothing else.
- If the above requirements are met and the PR is merged, send the examee a message on Discord letting them know they are ready for apprenticeship.

### CODE REVIEW

**Comment by Cherve3** [comment]
Everything looks correct but there seems to be a bak file added as well. If you could remove that file by amending your commit then it could be merged. 

I had trouble finding your [Trello task card](https://trello.com/c/qCi2AoVV/1886-lockesthethief-join-exam) related to this because you were not assigned to the card. To add yourself, there is a join button at the top right of the Trello card. 

Also, when the task is assigned and has a date, move the card to the programming section under the "Tasks In Progress" column. When the task is finished and needs review, move the card to "Ready for Review/Testing" column.

**Comment by Cherve3** [comment]
You will additionally need to "pull origin" because another pull request has been merged before this one.

**Comment by Lockeheede** [comment]
Hey, I removed the bak file and pressed Join on the card. However I’m having a hard time finding the card, not sure which Trello Board it is in.  Sent from Mail for Windows From: Cherve#7021Sent: Sunday, June 25, 2023 3:57 PMTo: P1Gaming/P1-OM-InfoCc: Prescott; AuthorSubject: Re: [P1Gaming/P1-OM-Info] lockes_thethief update (PR #22) You will additionally need to "pull origin" because another pull request has been merged before this one.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Lockeheede** [comment]
I’m also not sure where to pull origin.  Sent from Mail for Windows From: Cherve#7021Sent: Sunday, June 25, 2023 3:57 PMTo: P1Gaming/P1-OM-InfoCc: Prescott; AuthorSubject: Re: [P1Gaming/P1-OM-Info] lockes_thethief update (PR #22) You will additionally need to "pull origin" because another pull request has been merged before this one.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Cherve3** [comment]
I linked the card in my above comment but the card is at the bottom of the "Join Exams/Good First Tasks" column on Trello. If you are using GitHub Desktop there should be a button that says fetch origin or pull origin. Clicking that button will pull the updates.

**Comment by Cherve3** [comment]
Are you still wanting to finish this?

**Comment by Cherve3** [comment]
Never returned to update it. I believe we could undo the close if they do come back but its been nearly a month.

**Pull request closed without merging**
